version: '2'

services:
    front:
        #image: ekyna/nginx
        build: ./docker/front
        ports:
            - "80:80"
        links:
            - "engine:engine"
        volumes:
            - ".:/home/docker:ro"
            - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"

    engine:
    #    image: ekyna/php7
        build: ./docker/engine
        volumes:
            - ".:/home/docker:rw"
            - "./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
        ports:
            - "9080:22"
        links:
            - "db:db"
        working_dir: "/home/docker"
        environment:
            PHP_IDE_CONFIG: "serverName=symfony.dev"

    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "your_root_password"
            MYSQL_USER: "your_user"
            MYSQL_PASSWORD: "your_user_password"
            MYSQL_DATABAS: "your_database_name"
